import { StyleSheet,ImageStyle,ViewStyle,TextStyle} from "react-native";

interface DashboardScreen{
  container:ViewStyle
  mainInformationContainer:ViewStyle
  headerViewContainer:ViewStyle
  headerTitleContainer:ViewStyle
  mainTitle:TextStyle
  mainSubTitle:TextStyle
  mainOptionsContainer:ViewStyle
  cardsDashboardContainer:ViewStyle
  cardsDashboardBtn:ViewStyle
  headerViewContainerCard:ViewStyle
  headerViewContainerCardText:TextStyle
  headerViewContainerCardTextValue:TextStyle
  headerViewContainerCardIcon:ViewStyle
  cardsDashboardBtnLogo:ViewStyle
  cardsDashboardBtnAbout:TextStyle
  cardsDashboardBtnTitle:TextStyle
  cardsDashboardBtnLogoArrow:ViewStyle
}

const DashboardStyles : DashboardScreen = StyleSheet.create({
   container: {
    width:'100%',
    height:'100%',
    display:'flex',
    justifyContent: "space-between",
    alignItems:'center',
    flexDirection:'column',
    backgroundColor:'#F8FAFC'
  },
  mainInformationContainer:{
    width:'100%',
    height:'88%',
    display:'flex',
    justifyContent: "flex-start",
    alignItems:'center',
    flexDirection:'column',
    rowGap:15
  },
  headerViewContainer:{
    width:'95%',
    height:'20%',
    borderWidth:1,
    borderColor:'#96c4fd',
    borderRadius:10,
    backgroundColor:'#f1f8fe',
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
  },
  headerTitleContainer:{
    width:'95%',
    height:80,
    display:'flex',
    flexDirection:'column',
    alignItems:'flex-start',
    justifyContent:'space-around',
  },
  mainTitle:{
    width:'auto',
    height:'auto',
    fontSize:24,
    fontWeight:'bold',
    color:'#091431'
  },
  mainSubTitle:{
    width:'auto',
    height:'auto',
    fontSize:14,
    fontWeight:'bold',
    color:'#888fa0'
  },
  mainOptionsContainer:{
     width:'95%',
     height:'60%',
     display:'flex',
     justifyContent:'space-between',
     alignItems:'center',
     flexDirection:'column'
  },
  cardsDashboardContainer:{
    width:'100%',
    height:'48%',
       display:'flex',
     justifyContent:'space-between',
     alignItems:'center',
     flexDirection:'row'
  },
  cardsDashboardBtn:{
    width:'47%',
    height:'100%',
    display:'flex',
     justifyContent:'space-around',
     alignItems:'center',
     flexDirection:'column',
     borderWidth:1,
     borderColor:'#888fa041',
     borderRadius:10
  },
  headerViewContainerCard:{
    width:'33%',
    height:'85%',
     display:'flex',
     justifyContent:'space-around',
     alignItems:'center',
     flexDirection:'column',     
  },
  headerViewContainerCardText:{
    width:'auto',
    height:'auto',
    fontSize:12,
    color:'#888fa0'
  },
   headerViewContainerCardTextValue:{
    width:'auto',
    height:'auto',
    fontSize:14,
    color:'#091431',
    fontWeight:'bold',
    textAlign:'center'
  },
  headerViewContainerCardIcon:{
    width:30,
    height:30,
    display:'flex',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#5098fc31',
    borderRadius:5
  },
  cardsDashboardBtnLogo:{
    width:50,
    height:50,
    borderRadius:25,
    display:'flex',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#5098fc31',
  },
  cardsDashboardBtnAbout:{
    width:'90%',
    height:'auto',
    fontSize:12,
    color:'#888fa0',
    textAlign:'center'
  },
  cardsDashboardBtnTitle:{
    width:'auto',
    height:'auto',
    fontSize:15,
    color:'#091431',
    fontWeight:'bold'
  },
  cardsDashboardBtnLogoArrow:{
    width:30,
    height:30,
    borderRadius:15,
    display:'flex',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#5098fc31',
  },
})

export default DashboardStyles