import { StyleSheet,ImageStyle,ViewStyle,TextStyle} from "react-native";
import { Theme } from "@/theme/theme";

interface SettingsTypesStyles{
  container:ViewStyle
  headerFilesListContainer:ViewStyle
  arrowBackView:ViewStyle
  mainTitle:TextStyle
  optionsBox:ViewStyle
  mainContainerOptions:ViewStyle
  optionsBoxTitle:ViewStyle
  boxOptionsLogo:ViewStyle
  optionsBoxTitleDesc:ViewStyle
  optionsBoxDisplay:ViewStyle
  themeBtns:ViewStyle
  themeBtnsDesc:ViewStyle
  titleOptionsDesc:TextStyle
  titleOptionsDescAbout:TextStyle
  photosOptionsBox:ViewStyle
  photosOptionsBoxDesc:ViewStyle
  photosOptionsBoxQuality:ViewStyle
}
const SettingsStyles=(theme:Theme) : SettingsTypesStyles => StyleSheet.create({
   container: {
    display:'flex',
    width:'100%',
    height:'100%',
    justifyContent:'space-between',
    alignItems:'center',
    flexDirection:'column',
    backgroundColor:theme.background
    },
    headerFilesListContainer:{
    width:'95%',
    height:'7%',
    display:'flex',
    justifyContent:'flex-start',
    alignItems:'center',
    flexDirection:'row',
    columnGap:10
  },
  arrowBackView:{
    width:40,
    height:40,
    backgroundColor:'#5098fc31',
    borderRadius:5,
    display:'flex',
    justifyContent:'center',
    alignItems:'center'
  },
  mainTitle:{
    width:'auto',
    height:'auto',
    fontSize:22,
    fontWeight:'bold',
    color:theme.text
  },
  mainContainerOptions:{
    width:'100%',
    height:'93%',
    display:'flex',
    justifyContent:'space-around',
    alignItems:'center',
    flexDirection:'column'
  },
  optionsBox:{
    width:'95%',
    height:'31%',
    borderWidth:1,
    borderColor:theme.border,
    borderRadius:10,
    display:'flex',
    justifyContent:'space-around',
    alignItems:'center',
    flexDirection:'column',
  },
  optionsBoxTitle:{
    width:'95%',
    height:'22%',
    display:'flex',
    justifyContent:'flex-start',
    alignItems:'center',
    flexDirection:'row',
    columnGap:20,
    marginInline:'auto'
  },
   boxOptionsLogo:{
    width:45,
    height:45,
    borderRadius:25,
    display:'flex',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#5098fc31',
  },
  optionsBoxTitleDesc:{
    width:'78%',
    height:'100%',
    display:'flex',
    justifyContent:'space-around',
    alignItems:'flex-start',
    flexDirection:'column'
  },
  optionsBoxDisplay:{
    width:'95%',
    height:'65%',
    display:'flex',
     justifyContent:'space-between',
     alignItems:'center',
     flexDirection:'column',
     borderWidth:1,
     borderColor:'#888fa041',
     borderRadius:10,
     marginInline:'auto'
  },
  themeBtns:{
    width:'100%',
    height:'33%',
    display:'flex',
    justifyContent:'space-between',
    alignItems:'center',
    flexDirection:'row',
    paddingInline:10
  },
  themeBtnsDesc:{
    width:'auto',
    height:'100%',
    display:'flex',
    justifyContent:'flex-start',
    alignItems:'center',
    flexDirection:'row',
    columnGap:10
  },
  titleOptionsDesc:{
    fontSize:15,
    fontWeight:'bold',
    color:theme.text
  },
  titleOptionsDescAbout:{
    fontSize:12,
    color:'#888fa0'
  },
  photosOptionsBox:{
    width:'100%',
    height:'50%',
    display:'flex',
    justifyContent:'space-between',
    alignItems:'center',
    flexDirection:'row',
    paddingInline:10
  },
  photosOptionsBoxDesc:{
    width:'70%',
    height:'70%',
   display:'flex',
    justifyContent:'space-around',
    alignItems:'flex-start',
    flexDirection:'column' 
  },
  photosOptionsBoxQuality:{
    width:'auto',
    height:'auto',
    padding:5,
    borderWidth:1,
    borderColor:'#888fa041',
    display:'flex',
    justifyContent:'center',
    alignItems:'center',
    flexDirection:'row',
    columnGap:5,
    backgroundColor:'#96c4fd8c',
    borderRadius:4
  }
})

export default SettingsStyles